const names = require('./names')
const sayHi = require('./utils')
const data = require('./alternative-flavors')
require('./mind-grenade')
console.log(data)
sayHi('Susan')
sayHi(names.john)
sayHi(names.peter)